### ISSUE TITLE
[perf]: untranspiled template literal string is causing an error in IE11

### ISSUE THREAD

**Issue by markplewis** [Scrum/posthtml-beautify#224]
The template literal that's returned by the following function isn't being transpiled during the distribution build process:

Source file (`/src/index.js`):
```
const getIndent = level => `${eol}${indentString.repeat(level)}`;
```

So when I import `posthtml-beautify` into my project, `/lib/index.js` still contains a template literal:
```
getIndent = function (level) { return `${eol}${indentString.repeat(level)}` }
```

This breaks my app in IE11 because template literals are not supported by that browser.

**Comment by markplewis** [comment]
Sorry, I guess this isn't really a bug, since I shouldn't expect package authors to transpile their distribution code for me. I'll figure out how to do this in my own consuming app instead.

**Comment by markplewis** [comment]
Having said the above, it should be pretty easy to change a few build options in order to make the distributed code IE11-compatible, so I'll re-open this and leave it up to you to decide whether you're willing to make this change. I'm importing this package into a Nuxt application and I'm having a difficult time transpiling it, so doing so here in the package itself would be really helpful.

**Comment by Scrum** [comment]
@markplewis Hi, thanks for feedback, I will try to do downgrade in my free time to support older browsers.

Write to me is also very important to know the opinion and the desire to improve the product.

**Comment by Scrum** [comment]
@markplewis watch for https://github.com/Scrum/posthtml-beautify/pull/225

**Comment by markplewis** [comment]
Awesome! Thanks @Scrum! Much appreciated!

**Comment by markplewis** [comment]
@Scrum After _a lot_ of troubleshooting and experimentation, I finally solved my problem by setting `sourceType` to `unambiguous` in my Nuxt project's Babel configuration. [This comment](https://github.com/webpack/webpack/issues/4039#issuecomment-419284940) was the missing piece of the puzzle that helped me figure it out. I apologize for confusing everyone with my unnecessary pull request back in November.

**Comment by Scrum** [comment]
@markplewis Hi, no big deal. Contact anyway if you need help.
